### ISSUE TITLE
Created or modified entries appear twice

### ISSUE THREAD

**Issue by harlock974** [linuxmint/mintmenu#240] opened 2019-09-29 12:27 UTC
With Linux Mint 19.2 :
When a category is renamed it appears twice in the menu.
When an application shorcut is added, it appears also twice.
These double entries don't show in the menu editor, but only in the menu actually displayed.

![menu_editor](https://user-images.githubusercontent.com/6268242/65832480-57c5c100-e2d5-11e9-8594-ddf6f5fe1b09.png)

Here the "Education" menu has been renamed to "Science", and two shorctcut to programs have been added (Marée and Mimee). Science, Marée and Mimee now show twice in the menu displayed (I didnt succeeded to make a screenshot of the opened menu).

**Comment by harlock974** [comment] 2019-09-30 10:33
Ok here is the menu screenshot, with the double entries : 
![menu](https://user-images.githubusercontent.com/6268242/65871300-27425d80-e38f-11e9-97d9-6c033fcd95c3.png)

**Comment by xenopeek** [comment] 2020-01-12 18:27
Thanks for reporting the issue. This is an issue with the menu editor MenuLibre, not with mintMenu. Please uninstall MenuLibre and replace it with the menu editor Mozo. On Linux Mint 19.3 MATE that is the default menu editor.

The duplicate categories are caused by MenuLibre adding the category both to the file `~/.config/menus/mate-applications.menu` and in a file `~/.config/menus/applications-merged/user-category.menu`. Deleting the latter file removes the duplicate categories and duplicate launchers. The duplicate entries created by MenuLibre show up in all the menu applets (mintMenu, Main Menu and Menu Bar).

For reference, this is the same problem as described in https://github.com/linuxmint/linuxmint/issues/151.

**Closed by xenopeek** 2020-01-12 18:27 UTC
