### ISSUE TITLE
mintmenu is elevated from the bottom mate panel with compiz

### ISSUE THREAD

**Issue by tur1812** [linuxmint/mintmenu#121] opened 2015-01-01 04:58 UTC
Running 17.1.  Sometime I have a problem while open mintmenu (50% of times, random).
Menu "hovering in the air", centimeter above.
Played with compiz settings, but can't figure out a way to prevent it.

**Comment by monsta** [comment] 2015-03-26 15:03
@tur1812: workaround is to disable Place Windows plugin in Compiz settings.

**Comment by Yanpas** [comment] 2015-04-17 22:11
Don't know about MATE, in XFCE you are just to click do not reserve space on edges

**Comment by hiboudev** [comment] 2016-01-10 14:33
Hi,

I tried to fix this bug tweaking Compiz settings, but can't find a correct way actually. To disable the placement window is not a solution cause you end with all windows placed at top left of screen, a very poor behavior for a modern desktop...
I use Compiz cause this is almost the only composition solution that doesn't have tearing by default in Mint Mate 17.3, and the others are too slow (and not using a compositor on a modern computer is not a solution too).

This mintMenu/Compiz bug has been reported almost one year ago on Compiz launchpad : https://bugs.launchpad.net/compiz/+bug/1419346
I hardly understand why it takes so long time to fix this kind of tiny but annoying bug...

I don't know if this is just a bug in Compiz or the result of a bad interaction between the menu and Compiz, but the calendar opened by clicking the clock is well placed. 

Anyway, I don't have yet big knowledge in Linux stuff, but trying to fix this bug gave me an idea of how it should be managed :
1) Give to the mintMenu window a name, actually it doesn't have one.
2) Add in Compiz Placement plugin the ability to blacklist windows from placement, typically a user will add the windows that use self placement, like the mintMenu. To blacklist the mintMenu we will be able to use the window name given at 1).

Another idea : Do windows that use self placement have a flag ? If yes, Compiz Placement plugin would also have an option to blacklist windows with this flag.
Note, writing this, I'm thinking this is what force_placement_match does, but then, why it forces position of mintMenu ? Does mintMenu asks correctly to __*not*__ be placed ?

I hope someone in Mint team will read and consider this, cause it's already been a year that this is reported, and for a new Linux user (not my case but I install Linux to new users), to see this kind of bug in the main menu (one of the first thing a new user looks at) gives as first impression a feeling of something buggy and not finished. :(

**Comment by hiboudev** [comment] 2016-01-10 23:41
OK, so I found that I wasn't able to force position with CompizConfig Settings Manager cause of another bug : https://github.com/linuxmint/mate/issues/11

So I'm able to add a rule in Window Placement plugin > Windows with fixed position :
```
name=mintMenu.py
x=0
y=628
Keep in desktop area : you have to uncheck this!
```
This is only a temporary fix, cause you will probably need to change Y value at resolution change, menu change (adding items would change the height), panel move...

1) If you don't uncheck the "Keep in desktop area" checkbox, the issue is still there, so it seems that Compiz thinks the menu is under the taskbar, and it's why it elevates it.

2) Another thing, when I check the Y position of mintMenu window with "xwininfo" command, it gives 601. But to force the position in Compiz I have to give 628 to get the same visual result : what is the part concerned by this 27 pixels? I checked if this is the taskbar height, but no, the buggy gap between bar and menu doesn't change with taskbar height.

3) And last thing, with Compiz the menu doesn't have the thin white border (default Mate theme) that it has with Marco+compositor.

Maybe it's all related to the issue.

**Comment by Yanpas** [comment] 2016-01-10 23:44
As far as I remember it is possible to use xfwm4 with mate de. Tearing is fixed in master version of xfwm4.

**Comment by hiboudev** [comment] 2016-01-10 23:58
Yanpas : I found that Compton too can vsync, but it is really slower than Compiz when screen starts to be overwhelmed with windows. But unfortunately Compiz has also a random bug when resizing windows, sometimes it's not smooth at all, getting slower and resize at 5 frames per second. Except this, I love it.

**Comment by charlesbos** [comment] 2016-01-15 11:14
Like I said on the launchpad report, I think the real issue has got something to do with the Window Decoration plugin in Compiz. I found that disabling the plugin eliminates the issue and that adjusting the window title height (you can do this if you're using emerald, not sure about gtk-window-decorator) will make the size of the gap change.

**Comment by JDougherty** [comment] 2016-05-02 15:49
@monsta - Suggested workaround does not seem to work for me. Linux Mint 17.1 with MATE 1.8.1 and Compiz 0.9.11.3

As @charlesbos said, it seems the issue is the Window Decoration plugin. If I disable this one, the menu consistently is placed where it should be. That's not much of a workaround though because then I don't have window borders...

**Comment by JDougherty** [comment] 2016-05-02 15:53
Here's a better workaround, copied from the [launchpad bug](https://bugs.launchpad.net/compiz/+bug/1419346):

1) Enable the "Window Rules" compiz plugin
2) In the "Window Rules" settings, go to the "Size Rules" tab
3) Click the "New" button to add a new rule
4) In the "Edit" popup dialog, click the "+" button to add a match
5) In the "Edit Match" popup dialog, set "Type" to window class, value to "MintMenu.py", and click "Add"; the "Edit Match" dialog will close
6) Click "Close" in the "Edit" popup dialog, the "Edit" dialog will close. 

Should be all set at that point.

**Comment by BlushBerry** [comment] 2016-12-12 09:52
Brilliant @JDougherty this fix actually worked. No issues here.

**Comment by marcogiannini** [comment] 2016-12-13 16:16
@JDougherty thanks for the fix

**Comment by xenopeek** [comment] 2018-02-23 08:49
I tried to reproduce this on Linux Mint 18.3 MATE with Compiz and Window Decoration enabled (the default) and Place Windows enabled (not the default). Either there was more to the steps to reproduce this issue or it has been fixed in some component since.

If the issue happens again, please test against the latest mintmenu version, go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be mintmenu.

**Closed by xenopeek** 2018-02-23 08:49 UTC
Labels: confirmed
