### ISSUE TITLE
mintmenu sometimes not displayed at first click in composite mode

### ISSUE THREAD

**Issue by denispr** [linuxmint/mintmenu#115] opened 2014-11-09 12:50 UTC
In composite mode, sometimes (but not always), at first click, mintmenu displays only an empty rectangle. One has to click again to close it, then click once more to have it displayed properly.

**Comment by tur1812** [comment] 2015-01-01 04:37
Hi MONSTA! I'm also running 17.1 mate (with copmiz) an d have same problem as SISTYFIVE.
How exactly you have ffixed this issue?

**Comment by monsta** [comment] 2015-01-01 11:20
please read all the comments once again - it's a different issue

**Comment by tur1812** [comment] 2015-01-04 04:05
MONSTA: i know that this is a different issue, but.. From your comment (from 19 nov 2014) i can conclude that you've fixed bug with mintmenu when compiz  was compositor. So my question is HOW? because i'm have this bug. thank you.

**Comment by xenopeek** [comment] 2018-02-23 08:23
I can't reproduce this on Linux Mint 18.3 MATE with Marco + Compositing. As there have been no further updates on the original issue from late 2014 I'll assume it is no longer affecting users on current version and closing it.

**Closed by xenopeek** 2018-02-23 08:23 UTC
