### ISSUE TITLE
mintmenu icon disappears from panel

### ISSUE THREAD

**Issue by bits01** [linuxmint/mintmenu#145] opened 2015-11-28 04:46 UTC
Linux Mint 17.2 Rafaela, x64 MATE edition
MATE 1.10
mintmenu 5.6.4

After some recent updates (not sure exactly which) the mintMenu no longer shows up in the panel. I think it's there as I can see a mintMenu.py process running but it's missing its icon. I tried:

```
mintmenu --reset
mate-panel --reset
```

but it didn't help.

If I try to add it by hand to the panel, I see it when I search for it but without the icon (see the screenshot linked below).

I also tried creating a fresh user but it has the same problem, so the issue seems to be system wide.

I tried a force re-install of mintupdate and mint-meta-mate and it did not help either.

/var/log/syslog does not show anything interesting.

Here's a screenshot:
http://forums.linuxmint.com/download/file.php?id=26102&mode=view
or
http://i.imgur.com/RR5Pfsl.png

And the thread in the forums:
http://forums.linuxmint.com/viewtopic.php?f=206&t=210166

**Comment by bits01** [comment] 2015-11-28 05:19
If I run mintmenu by hand, I see this warning:
```
/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py:50: RuntimeWarning: You have imported the Gtk 2.0 module.  Because Gtk 2.0 was not designed for use with introspection some of the interfaces and API will fail.  As such this is not supported by the pygobject development team and we encourage you to port your app to Gtk 3 or greater. PyGTK is the recomended python module to use with Gtk 2.0
  warnings.warn(warn_msg, RuntimeWarning)
```
Not sure whether it's significant or just a warning that can be safely ignored.

**Comment by monsta** [comment] 2015-12-03 12:28
Please try mintMenu 5.6.5 from http://packages.linuxmint.com/pool/main/m/mintmenu/ - it might fix it.

**Comment by bennabiy** [comment] 2015-12-03 13:49
I also had this issue, and 5.6.5 did not fix it. I verified that pre-update, I had a menu, and post update, I lost my menu, but I could not tell you which package broke it.

**Comment by bits01** [comment] 2015-12-03 18:49
Unfortunately 5.6.5 doesn't fix it either. I tried again mintmenu --reset && mate-panel --reset, still no luck.
There's a mintmenu.py python process running and I'm pretty sure that the menu is there in the panel it's just the icon that is broken/missing and it probably renders as 1 pixel or something like that.

Or maybe there is something else that's wrong with it as the Super_L key still doesn't bring it up, I'd think that at least the keyboard should work.

Any ideas how to debug this please?

**Comment by monsta** [comment] 2015-12-03 18:58
Can you repost the screenshot please? We currently have issues on the server at linuxmint.com... the forum attachment can't be loaded.

Also, are there any related error messages in ```~/.xsession-errors```?
(the warning posted above can be ignored - it's been there since MATE 1.6 and isn't related to this issue)

**Comment by bits01** [comment] 2015-12-03 19:05
I removed .xsession-errors and started a new session. This is what it has:

** Message: Initializing gksu extension...
Initializing caja-open-terminal extension

(mate-panel:26199): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(mate-panel:26199): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py:50: RuntimeWarning: You have imported the Gtk 2.0 module.  Because Gtk 2.0 was not designed for use with introspection some of the interfaces and API will fail.  As such this is not supported by the pygobject development team and we encourage you to port your app to Gtk 3 or greater. PyGTK is the recomended python module to use with Gtk 2.0
  warnings.warn(warn_msg, RuntimeWarning)
^[[35;01mwarning: value_int() Failed to convert data[1433908487.17816]:invalid literal for int() with base 10: '1433908487.17816'  ^[[0m
"sni-qt/26252" WARN  11:02:04.497 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE
^[[31;01merror: Unable to find hp-upgrade --notify on PATH.^[[0m
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2400003 (Virtual Ma)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.

** (caja:26219): CRITICAL **: caja_menu_provider_get_background_items: assertion 'CAJA_IS_MENU_PROVIDER (provider)' failed
mintUpdate: no process found

(mintUpdate.py:26414): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:26414): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:26414): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:26414): libglade-WARNING **: unknown attribute `swapped' for <signal>.

**Comment by bits01** [comment] 2015-12-03 19:12
And here's the screenshot again:
http://i.imgur.com/RR5Pfsl.png

**Comment by bennabiy** [comment] 2015-12-03 22:09
I found that the package:
python-xlib   0.14+20091101-1ubuntu3~trusty    Interface for Python to the X11 Protocol

is the offending update (level3 update in mintupdate) which should be marked as unsafe. If you can revert to the previous version (0.14+20091101-1ubuntu2)

if you do a:
sudo apt-get install python-xlib=0.14+20091101-1ubuntu2 

it should downgrade the package and you just need to log out/in.

**Comment by bits01** [comment] 2015-12-04 00:11
Thank you very much. This fixed the problem.
For now I'm holding back the package, until fixed:
```
apt-mark hold python-xlib
apt-mark showhold
```

Is someone going to notify those in charge of python-lib of the breaking changes?

**Comment by MichaelTunnell** [comment] 2015-12-04 01:36
The following comment is totally off-topic but might be useful. :)

```
apt hold python-xlib
apt held
```

https://github.com/linuxmint/mintsystem/blob/master/usr/local/bin/apt

I wrote an article on that as well, http://www.howtogeek.com/234583/simplify-command-line-package-management-with-apt-instead-of-apt-get/ :)

**Comment by bits01** [comment] 2015-12-04 01:45
@MichaelTunnell Thanks! I didn't know about it.

**Comment by MichaelTunnell** [comment] 2015-12-04 01:55
:+1:

**Comment by monsta** [comment] 2015-12-04 08:25
@clefebvre: can you please take a look at this?

**Comment by bits01** [comment] 2015-12-04 15:23
And in the Add Panel dialog as posted in my screenshot, are we supposed to see an icon for mintMenu? Now that I rolled back python-xlib the mintMenu shows up in the mate-panel and it works but in the Add Panel dialog it still doesn't have an icon. Maybe that's normal, just looking for confirmation or maybe it's another bug that it doesn't.

**Comment by bits01** [comment] 2015-12-05 16:41
I see that Mint 17.3 Rosa has been released. Does anyone know whether this issue is fixed in 17.3?

**Comment by bennabiy** [comment] 2015-12-06 23:59
I can confirm it is not fixed in Rosa. I have hit this issue with 17.1
- 17.3 and with both mintmenu 5.6.4 an 5.6.5


-- 
-- 
בן–נביא  דרוּשׁ  שׁל  יוֹסף
ben-Nabiy Derush of Yowceph
The Yellow Deli


On Sat, 05 Dec 2015 08:41:15 -0800
bits01 <notifications@github.com> wrote:

> I see that Mint 17.3 Rosa has been released. Does anyone know whether
> this issue is fixed in 17.3?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/linuxmint/mintmenu/issues/145#issuecomment-162220715


-- 
-- 
בן–נביא  דרוּשׁ  שׁל  יוֹסף
ben-Nabiy Derush of Yowceph
The Yellow Deli

**Comment by bits01** [comment] 2015-12-07 00:00
Bummer. Hopefully the devs will chime in soon.

**Comment by bennabiy** [comment] 2015-12-07 00:14
There are a few other major issues which are currently on their plate,
with the downing of their server, etc, so I am not expecting prompt
addressing, although it would be nice. I have talked with them in IRC
about the issue, and we want to troubleshoot it. I am wondering if it
is hardware / software compatibility.

I am using Native Intel Graphics on a i5 with open drivers - Gigabyte
motherboard, UEFI install.


-- 
-- 
בן–נביא  דרוּשׁ  שׁל  יוֹסף
ben-Nabiy Derush of Yowceph
The Yellow Deli


On Sun, 06 Dec 2015 16:00:18 -0800
bits01 <notifications@github.com> wrote:

> Bummer. Hopefully the devs will chime in soon.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/linuxmint/mintmenu/issues/145#issuecomment-162376639


-- 
-- 
בן–נביא  דרוּשׁ  שׁל  יוֹסף
ben-Nabiy Derush of Yowceph
The Yellow Deli

**Comment by bits01** [comment] 2015-12-30 19:28
Any updates on this issue? Is it safe to now let `python-xlib` update?

**Comment by bennabiy** [comment] 2015-12-30 21:55
As far as I can tell, the issue is still there. I am wondering if it is
hardware related, as I do a fresh install with Virtualbox, and I do not
get the issue, but on my actual machine, I can recreate it with a fresh
install and just installing that one update.

What hardware do you run? I am running an i5 with Intel graphics.


-- 
-- 
בן–נביא  דרוּשׁ  שׁל  יוֹסף
ben-Nabiy Derush of Yowceph
The Yellow Deli


On Wed, 30 Dec 2015 11:28:37 -0800
bits01 <notifications@github.com> wrote:

> Any updates on this issue? Is it safe to now let `python-xlib` update?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/linuxmint/mintmenu/issues/145#issuecomment-168060299


-- 
-- 
בן–נביא  דרוּשׁ  שׁל  יוֹסף
ben-Nabiy Derush of Yowceph
The Yellow Deli

**Comment by bits01** [comment] 2015-12-30 22:00
I do have a Xeon CPU with built-in graphics, but I'm not sure that matters as I use a VNC server, the server itself boots in console mode and is headless, I just start a VNC server and connect to it.

**Comment by bennabiy** [comment] 2016-02-07 02:01
So far I have had every LTSP lab I run come down with this issue. I am tempted to grab the source of both packages and check the diff. Have you filed a bug against python-xlib?

**Comment by clefebvre** [comment] 2016-04-19 13:11
https://github.com/LiuLang/python3-xlib/pull/7/files

**Comment by clefebvre** [comment] 2016-04-19 13:11
https://github.com/LiuLang/python3-xlib/issues/6
and https://bugs.launchpad.net/ubuntu/+source/python-xlib/+bug/1482844

**Comment by clefebvre** [comment] 2016-04-19 13:13
With the new python-xlib, can you rm .Xauthority and relogin to see if that works?

**Comment by bennabiy** [comment] 2016-04-21 14:18
Still broken...


-- 
-- 
בן–נביא  דרוּשׁ  שׁל  יוֹסף
ben-Nabiy Derush of Yowceph
The Yellow Deli


On Tue, 19 Apr 2016 06:13:46 -0700
Clement Lefebvre <notifications@github.com> wrote:

> With the new python-xlib, can you rm .Xauthority and relogin to see
> if that works?
> 
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/linuxmint/mintmenu/issues/145#issuecomment-211919089


-- 
-- 
בן–נביא  דרוּשׁ  שׁל  יוֹסף
ben-Nabiy Derush of Yowceph
The Yellow Deli

**Comment by clefebvre** [comment] 2016-04-22 08:55
Can you try http://mirrors.kernel.org/ubuntu/pool/universe/p/python-xlib/python-xlib_0.14+20091101-5_all.deb?

**Comment by bennabiy** [comment] 2016-04-22 14:23
Still missing. Reverting back to _0.14+20091101-1ubuntu2


-- 
-- 
בן–נביא  דרוּשׁ  שׁל  יוֹסף
ben-Nabiy Derush of Yowceph
The Yellow Deli


On Fri, 22 Apr 2016 01:55:26 -0700
Clement Lefebvre <notifications@github.com> wrote:

> Can you try
> http://mirrors.kernel.org/ubuntu/pool/universe/p/python-xlib/python-xlib_0.14+20091101-5_all.deb?
> 
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/linuxmint/mintmenu/issues/145#issuecomment-213336941


-- 
-- 
בן–נביא  דרוּשׁ  שׁל  יוֹסף
ben-Nabiy Derush of Yowceph
The Yellow Deli

**Comment by clefebvre** [comment] 2016-05-17 09:09
Something else must be at play here. On Mint 18 ALPHA, using python-xlib 0.14+20091101-5, mintmenu appears without problems.

**Comment by bennabiy** [comment] 2016-08-05 02:12
It appears to be related to displays over X remotely (not using SSH). I can get it to appear using SSH but not just direct X forwarding. I have an issue in with python-xlib and am using the latest from the ppa 0.16 .

**Comment by bennabiy** [comment] 2016-08-05 02:19
I just confirmed that it is the same issue linked above https://github.com/LiuLang/python3-xlib/pull/7/files 

If I go to the remote server, and type xhost +{serverhostname} and then try, it works.

**Comment by bits01** [comment] 2016-08-05 04:28
It happens via VNC (tigervncserver 1.6.0-3ubuntu1) too.

**Comment by bennabiy** [comment] 2016-08-08 14:01
Working with upstream python-xlib, we traced the issue down. @clefebvre If you pull in at least python-xlib 0.16 and make this change, it should work. https://github.com/python-xlib/python-xlib/issues/53

**Comment by bennabiy** [comment] 2016-08-08 14:02
It was an issue which only showed itself on python2.7 (the fix above is for python3).

**Comment by bits01** [comment] 2016-11-25 19:22
What's the status on this issue please? Safe to let python-xlib update to the latest on 17.3 Rosa?

**Comment by rootchick** [comment] 2016-11-29 20:09
I'm having this issue too on Mint 18 LTSP thin clients.  Works over VNC though.

**Comment by bennabiy** [comment] 2016-12-01 15:07
As I said before, the issue has been *mostly* fixed upstream. If you pull in the upstream python-xlib, it will work in the LTSP environment, as well as on the machine itself, but funnily, it breaks in x2go (whereas x2go worked when it was broken)!

**Comment by xenopeek** [comment] 2018-02-23 09:39
Linux Mint 19 will have python-xlib 0.20. LMDE 3 will still use python-xlib 0.14. For both Linux Mint 18.x and upcoming LMDE 3 you can easily install that python-xlib version and for Linux Mint 17.x and LMDE 2 it is also installable with a bit more work. Given the raised concerns in previous comment I assume porting python-xlib version 0.16 or newer to previous Linux Mint versions wasn't done as a default.

For users still affected by this issue (if the issue was indeed caused by python-xlib and hasn't been solved since the above analysis in some other component) I would suggest to try installing python-xlib 0.20.

For Linux Mint 18.x you can download the .deb file from here https://packages.ubuntu.com/bionic/python-xlib. If it doesn't work and you want to downgrade to the previous version you can run `apt install python-xlib/xenial`.

For Linux Mint 17.x you would download the same package as for Linux Mint 18.x but before installing it you must first also download and install a newer python-six version from here https://packages.ubuntu.com/bionic/python-six. If it doesn't work and you want to downgrade to the previous version you can run `apt install python-six/trusty python-xlib/trusty`.

For upcoming LMDE 3 you can download the .deb file from here https://packages.debian.org/buster/python-xlib. If it doesn't work and you want to downgrade to the previous version you can run `apt install python-xlib/stretch`.

For LMDE 2 you would download the same package as for upcoming LMDE 3 but before installing it you must first also download and install a newer python-six version from here https://packages.debian.org/buster/python-six. If it doesn't work and you want to downgrade to the previous version you can run `apt install python-six/jessie python-xlib/jessie`.

**Closed by xenopeek** 2018-02-23 09:39 UTC
