### ISSUE TITLE
mintMenu apps not showing

### ISSUE THREAD

**Issue by SOTVM** [linuxmint/mintmenu#270] opened 2022-03-15 12:50 UTC
Sorry about my "french", i don`t speak english, i am russian.
```
sudo apt purge mintmenu
rm -rf ~/.linuxmint/mintMenu ~/.config/mintmenu  ~/.config/menus
```
+ with Dconf Editor deleting /com/linuxmint/mintmenu

`sudo apt install mintmenu`
under root or another user - OK
under my login - NO
showing only Favorite
What can i do? (Smokie 1976) :)
![20220314-102200](https://user-images.githubusercontent.com/19145086/158381335-41c64b03-d834-4429-b243-cb6616952a8a.png)

**Comment by xenopeek** [comment] 2022-03-15 17:07
With the steps you provided I tried but failed on Linux Mint 20.3 MATE to reproduce the issue. After removing it fully as you detailed, installing it anew mintmenu and then adding it back to the panel it works just as before: all categories show application icons & names.

I suggest you take help from the forums to troubleshooting this further. There is a forum for MATE: https://forums.linuxmint.com/viewforum.php?f=206. If you create a new topic there please do mention your Linux Mint version (if you're not sure run `inxi -S` on the terminal to find out).

If after troubleshooting it turns out this is a reproducible bug in mintmenu you can reopen this issue here. Closing it for now.

**Closed by xenopeek** 2022-03-15 17:07 UTC

**Comment by SOTVM** [comment] 2022-03-16 11:24
Проблему решил :)
Какой то из .desktop файлов в каталоге ~/.local/share/applications/wine
не давал нормально  работать  плвгину applications,
Хотел найти какой именно файл вызвал эту проблему, но терпения не хватило, т.е. их много :(
Просто удалил весь каталог

**Comment by SOTVM** [comment] 2022-03-17 05:12
Проблема была в этом файле.
The problem was in this file.
![20220317-120604](https://user-images.githubusercontent.com/19145086/158741450-e35163b7-59b7-4319-8f94-3616abd1adca.png)
![20220317-120229](https://user-images.githubusercontent.com/19145086/158741473-a0c32a2f-482d-468b-ad8f-c6154bde4b21.png)
