### ISSUE TITLE
Graphical glitches on desktop after setting transparency of MATE mintmenu

### ISSUE THREAD

**Issue by Chugajstyr** [linuxmint/mintmenu#146] opened 2015-12-14 23:16 UTC
After upgrading Linux Mint 17.2 MATE x64 to latest 17.3, I tried to set transparency in mintmenu options (like it was before upgrade), and got nothing - transparency doesnt changed. But after that I see strange artifacts on my desktop. Tried reinstall mintmenu - its doesnt help.
![screenshot at 2015-12-11 00 05 58 v01](https://cloud.githubusercontent.com/assets/16296772/11796950/2e9f1c8c-a2c8-11e5-8a46-11ecc44b8b82.png)
![screenshot at 2015-12-14 21 49 46](https://cloud.githubusercontent.com/assets/16296772/11796955/33764294-a2c8-11e5-9701-73389ed6aa5b.png)

**Comment by marsjaninzmarsa** [comment] 2017-11-11 14:14
I don't believe it has anything to do with mintmenu.

**Comment by xenopeek** [comment] 2018-02-23 09:44
This indeed does not appear to have been caused by mintmenu. Given the age of the issue I'm closing it.

If the issue happens again, please test against the latest mintmenu version, go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be mintmenu.

**Closed by xenopeek** 2018-02-23 09:44 UTC
