### ISSUE TITLE
Install additional software dialog doesnt work with keyboard

### ISSUE THREAD

**Issue by philipzae** [linuxmint/mintmenu#127] opened 2015-02-21 07:23 UTC
I opened up the mintmenu and typed a package i wanted to install, then pressed enter and the 'Install additional software?' dialog appeared. Then i press the right key to move to the install button and pressed enter and it pressed the cancel button. After testing it more, i see that if i had pressed spacebar instead of enter, it would have worked correctly.

**Comment by monsta** [comment] 2015-03-02 08:39
That dialog is shown by apturl, so it's not a mintMenu issue.
You can reproduce it by running "apturl apt://package_name" in the terminal.

**Comment by philipzae** [comment] 2015-03-04 00:34
Any ideas how i can send this bug to the people handling apturl?

**Comment by GLolol** [comment] 2015-03-04 01:01
I'd assume at the Bugs section of https://bugs.launchpad.net/ubuntu/+source/apturl, their launchpad URL.

**Comment by monsta** [comment] 2015-03-04 05:59
Linux Mint uses an old version of apturl (newer versions don't work well with some Mint apps, e.g. mintWelcome).
For now, you can file a bug in "linuxmint" project on launchpad, we'll see if we can do something about it.

**Comment by xenopeek** [comment] 2018-02-23 09:04
Linux Mint 18.3 use apturl 0.5.2 which seems to be same version as upstream. The issue can still be reproduced with that: apturl doesn't let you navigate the Cancel and Install buttons with arrow keys or tab key. I found that you can press alt + i to highlight the Install button and then press enter to select it. In any case, apturl feature request can't be implemented in mintmenu so closing this.

**Closed by xenopeek** 2018-02-23 09:04 UTC
Labels: confirmed
